

# cmake/CPackConfig.cmake

set(CPACK_PACKAGE_NAME "TB64")
set(CPACK_THREADS 4)
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "pearlover912@gmail.com")

set(CPACK_SOURCE_TZ OFF)
set(CPACK_SOURCE_TXZ OFF)
set(CPACK_SOURCE_TGZ OFF)
set(CPACK_SOURCE_TBZ2 OFF)
set(CPACK_BINARY_STGZ OFF)
set(CPACK_BINARY_TGZ ON)
set(CPACK_BINARY_ZIP ON)

# Optional extras
set(CPACK_PACKAGE_VENDOR "Franktankbank")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "TB64 - A niche tool to encode text in base64 3 times. (cpp version)")
set(CPACK_STRIP_FILES TRUE)
set(CPACK_VERBATIM_VARIABLES TRUE)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")

# Linux binary packages
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(CPACK_BINARY_DEB ON)
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
    set(CPACK_DEBIAN_PACKAGE_SECTION utils)
    # add set(CPACK_DEBIAN_PACKAGE_CONFLICTS <Insert Conflicting Packages Here>) when the other flavors of tb64 are packaged
endif()
